### ISSUE TITLE
[FEAT] 참여 대외활동 기반 자기소개서 자동생성 기능 구현

### ISSUE THREAD

**Issue by Leeyoujin00** [hi-sujung/msa-portfolio#1]
## 📌 이슈 내용

Chat GPT API 활용 참여 대외활동 및 진로 분야 기반 자기소개서 자동생성 기능 구현

## 💼 작업 목록

- [x] Open AI key 발급
- [x] 기능 구현

**Comment by Leeyoujin00** [comment]
구현 완료

**Comment by suhyenim** [comment]
수고하셨습니다😀
